[workspace]
resolver = "2"
members = ["runtime", "clock", "shell", "sum", "fib", "smp", "gpio", "fb", "irq", "mmu", "dma", "pwm", "i2c", "spi", "uart1", "sd", "uart0", "irqcore", "lirq", "mva", "periphs", "debug", "bench"]

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
